# combined_extraction.py

# a wrapper module to combine the output of Week 3's entity extraction and Week 6's signal extraction
# code generated by Copilot 

from pathlib import Path
import spacy
from scripts.Signal_Extraction.signal_extraction import SignalExtractor
from ..NER.entity_extraction import add_entity_extractor

# Wraps the Week 3's spaCy pipeline so Week 6's SignalExtractor can call 
# extract_all(text) and receive those structured entities

class Week3EntityWrapper:
    
    def __init__(self, taxonomy_path):
        # Load spaCy and attach Week 3 entity extractor
        self.nlp = spacy.load("en_core_web_sm")
        self.nlp = add_entity_extractor(self.nlp, taxonomy_path)

    def extract_all(self, text):
        doc = self.nlp(text)
        out = []

        for ent in doc.ents:
            out.append({
                "label": ent.label_,
                "span_text": ent.text,
                "start": ent.start_char,
                "end": ent.end_char
            })

        return out


def build_combined_extractor():
    script_dir = Path(__file__).resolve().parent
    taxonomy_path = script_dir.parent / "SQL_Queries" / "canonical_amenities.json"

    week3 = Week3EntityWrapper(taxonomy_path)
    combined = SignalExtractor(taxonomy_path=taxonomy_path, entity_extractor=week3)
    return combined

# combined output from weeks 3 and 6 should be 'Suitable for search indexing and filtering'
# output needs to be efficiently searchable